# Generated by Django 4.2.14 on 2024-08-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_milage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milage',
            options={'ordering': ('-year',), 'verbose_name': 'пробег', 'verbose_name_plural': 'пробег'},
        ),
    ]
